### PR TITLE
D9 compatibility

### PR DESCRIPTION
**Pull request by bia-wtag**
# Background
This module is not currently Drupal 9 compatible as shown in the `upgrade_status` report. For upgrading, the dependencies are updated, deprecated code was removed and info.yml was updated.

# Goal
- Module is D9 compatible.

# Acceptance
- Functionalities work.
- No error from `upgrade_status` and d9 compatible.

# Workflow
# Local testing
# Site Usable Link

### CODE REVIEW

**Comment by rainer-friederich** [comment]
Just curious:
Are the changes from https://github.com/bmcclure/drupal-views_selective_filters/pull/4/files not needed?

**Comment by bia-wtag** [comment]
> Just curious:
> Are the changes from https://github.com/bmcclure/drupal-views_selective_filters/pull/4/files not needed?

I am not quite sure. I haven't changed anything from .inc files as there seems to be no incompatible code.

**Review by zar-wtag — APPROVED** [review]
Looks good.

**Review by the-wtag — APPROVED** [review]

**Review by adi-wtag — APPROVED** [review]

**Review by rainer-friederich — APPROVED** [review]
LGTM, no actual clue if it will work but let's find out :)

**Review by Wickeey — APPROVED** [review]

**Pull request merged**
